name: Continuous Integration

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: tab character check
        run: if grep -P '\t' -r ices/* fixed/*; then exit 1; fi

      - name: Build
        uses: ./.github/actions/build

      - run: ./target/release/glacier
